sonar.projectKey=real-estate-app
sonar.projectName=Real Estate App

sonar.sources=backend,frontend

sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**/*.test.js

sonar.exclusions=backend/node_modules/**,backend/data/**
